### ISSUE TITLE
不支持在源帖中，嵌入html 代码吗？

### ISSUE THREAD

**Issue by luckypoemster** [Tuzilow/CoinRailgun#1]
hi.

我用你这个程序搭建了博客: https://aesthetic-twilight-fb70db.netlify.app/ ,不过我在访问此帖：
https://aesthetic-twilight-fb70db.netlify.app/categories/blog/pretty-grassland/ 和
https://aesthetic-twilight-fb70db.netlify.app/categories/blog/hf/ 时，嵌入的html代码都未被渲染，怎么解决问题？
谢谢回复！

**Comment by QiYuOr2** [comment]
https://github.com/QiYuOr2/CoinRailgun/blob/6c636bf0fdd7d3fdbabb9bf509c72af1aafbb030/lib/utils/post.js#L8-L9
可以在 markdown-it 的配置里增加 `html: true` 配置项，以允许原样输出

```js
const md = require('markdown-it')({ 
  html: true,
  highlight: function (str, lang) { 
    //...
  },
)
```

**Comment by luckypoemster** [comment]
hi.

我改了那个文件，但是我需要重新运行npm install -g coinrailgun吗？我运行它没有用吧？是不是你要去https://www.npmjs.com/ ，更新一下coinrailgun呢？

**Comment by QiYuOr2** [comment]
旧账号密码忘了，您可以考虑使用市面上更优秀的博客生成工具，或是参考制作一个自己的工具。
如果一定要使用该项目可以尝试在本地修改代码后使用 `npm link` 链接到全局

**Comment by luckypoemster** [comment]
git clone https://github.com/luckypoemster/CoinRailgun
cd CoinRailgun
npm install (这一步到现在10几分钟了，还没完成）
然后node bin/crn.js吗？‘使用 npm link 链接到全局’-具体怎么做？
谢谢你！

**Comment by luckypoemster** [comment]
$ npm install
npm warn old lockfile
npm warn old lockfile The package-lock.json file was created with an old version of npm,
npm warn old lockfile so supplemental metadata must be fetched from the registry.
npm warn old lockfile
npm warn old lockfile This is a one-time fix-up, please be patient...
npm warn old lockfile
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

**Comment by QiYuOr2** [comment]
依赖用了旧的 taobao 源，安装时会报错，可以尝试删除 package-lock.json 再执行 npm install
npm link 参考官方文档 https://docs.npmjs.com/cli/v9/commands/npm-link

**Comment by luckypoemster** [comment]
果然好了。谢谢。我没有使用npm link，就用了node bin/crn.js而已.
https://creative-taiyaki-a81feb.netlify.app/

**Comment by luckypoemster** [comment]
hi.你好.
我按照这个项目https://github.com/Kuro32183/nextjs-ts-mdblog-test ,安装了一个静态博客.它也是基于nodejs的.竟然遇到了之前在你这里遇到的问题,甚至更糟,此博文https://ntmb.netlify.app/pg除了不能渲染为播放器之外,竟然连html codes也不显示了.
我向原作者提问了,他未回复.你如果有空,能帮忙看看他这个项目的源码,该改哪个文件才能解决问题? 
我尝试修改了它的[next.config.js](https://github.com/Kuro32183/nextjs-ts-mdblog-test/blob/main/next.config.js)文件,试图加入 html: true,  但是根本没有效果.
多谢你帮这个忙. 上帝保佑你人生路路通.

**Comment by QiYuOr2** [comment]
> hi.你好. 我按照这个项目https://github.com/Kuro32183/nextjs-ts-mdblog-test ,安装了一个静态博客.它也是基于nodejs的.竟然遇到了之前在你这里遇到的问题,甚至更糟,此博文[https://ntmb.netlify.app/pg除了不能渲染为播放器之外,竟然连html](https://ntmb.netlify.app/pg%E9%99%A4%E4%BA%86%E4%B8%8D%E8%83%BD%E6%B8%B2%E6%9F%93%E4%B8%BA%E6%92%AD%E6%94%BE%E5%99%A8%E4%B9%8B%E5%A4%96,%E7%AB%9F%E7%84%B6%E8%BF%9Ehtml) codes也不显示了. 我向原作者提问了,他未回复.你如果有空,能帮忙看看他这个项目的源码,该改哪个文件才能解决问题? 我尝试修改了它的[next.config.js](https://github.com/Kuro32183/nextjs-ts-mdblog-test/blob/main/next.config.js)文件,试图加入 html: true, 但是根本没有效果. 多谢你帮这个忙. 上帝保佑你人生路路通.

https://github.com/Kuro32183/nextjs-ts-mdblog-test/blob/fb241ca3fb667bfd3616050f9818ca2c6c548b30/src/lib/markdownToHtml.ts#L1-L2  请自行查询这两个库的文档
